DROP DATABASE IF EXISTS agenda;

CREATE DATABASE IF NOT EXISTS agenda;

USE agenda;

CREATE TABLE contactos(
 id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
 nombre VARCHAR(55) NOT NULL,
 numero VARCHAR(14) NOT NULL
);
